# Generated by Django 4.0.3 on 2022-03-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animals',
            old_name='type',
            new_name='type1',
        ),
    ]
